title: Ugyen Norbu 
description: "Portfolio of Ugyen Norbu, a software engineer and UI designer specializing in web development."

url: 
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
    github: https://github.com/
    twitter: https://x.com/home?lang=en
    facebook: https://www.facebook.com/
    email: 02240369.csr@rub.edu.bt
    linkedin: 
    youtube: https://www.youtube.com/
    tumblr: 

google_analytics: "your-google-analytics-id"

disqus:
    shortname: Ugay Nobu 
